import type { FlashCard, FlashcardDeck, Achievement } from './types'

// mockUnits is kept for reference only; the live curriculum comes from
// data/curriculum/*.json loaded via lib/curriculum/index.ts
const mockUnits = [
  {
    id: 'unit-1',
    title: 'Greetings & Basics',
    titleNl: 'Begroetingen & Basis',
    description: 'Learn how to say hello, introduce yourself, and handle everyday greetings.',
    order: 1,
    color: '#3b82f6',
    isCompleted: true,
    progress: 100,
    lessons: [
      {
        id: 'l-1-1',
        title: 'Hello & Goodbye',
        titleNl: 'Hallo & Tot Ziens',
        description: 'Essential greetings for any situation',
        unit: 1,
        order: 1,
        type: 'vocabulary',
        difficulty: 'beginner',
        estimatedMinutes: 5,
        xpReward: 50,
        isCompleted: true,
        isLocked: false,
        completedAt: '2024-01-20',
      },
      {
        id: 'l-1-2',
        title: 'Introducing Yourself',
        titleNl: 'Jezelf Voorstellen',
        description: 'Tell people your name and where you\'re from',
        unit: 1,
        order: 2,
        type: 'conversation',
        difficulty: 'beginner',
        estimatedMinutes: 8,
        xpReward: 75,
        isCompleted: true,
        isLocked: false,
        completedAt: '2024-01-21',
      },
      {
        id: 'l-1-3',
        title: 'Numbers 1–20',
        titleNl: 'Getallen 1–20',
        description: 'Count from one to twenty in Dutch',
        unit: 1,
        order: 3,
        type: 'vocabulary',
        difficulty: 'beginner',
        estimatedMinutes: 6,
        xpReward: 60,
        isCompleted: true,
        isLocked: false,
        completedAt: '2024-01-22',
      },
    ],
  },
  {
    id: 'unit-2',
    title: 'Daily Life',
    titleNl: 'Het Dagelijks Leven',
    description: 'Vocabulary and phrases for your everyday routine.',
    order: 2,
    color: '#8b5cf6',
    isCompleted: false,
    progress: 40,
    lessons: [
      {
        id: 'l-2-1',
        title: 'Food & Drink',
        titleNl: 'Eten & Drinken',
        description: 'Essential food vocabulary and ordering at a café',
        unit: 2,
        order: 1,
        type: 'vocabulary',
        difficulty: 'beginner',
        estimatedMinutes: 8,
        xpReward: 75,
        isCompleted: true,
        isLocked: false,
        completedAt: '2024-01-23',
      },
      {
        id: 'l-2-2',
        title: 'Shopping',
        titleNl: 'Winkelen',
        description: 'Ask for items, prices, and understand shop signs',
        unit: 2,
        order: 2,
        type: 'conversation',
        difficulty: 'beginner',
        estimatedMinutes: 10,
        xpReward: 80,
        isCompleted: false,
        isLocked: false,
      },
      {
        id: 'l-2-3',
        title: 'Telling the Time',
        titleNl: 'De Tijd Vertellen',
        description: 'Read clocks and discuss schedules',
        unit: 2,
        order: 3,
        type: 'grammar',
        difficulty: 'beginner',
        estimatedMinutes: 7,
        xpReward: 65,
        isCompleted: false,
        isLocked: false,
      },
      {
        id: 'l-2-4',
        title: 'At Home',
        titleNl: 'Thuis',
        description: 'Rooms, furniture, and household vocabulary',
        unit: 2,
        order: 4,
        type: 'vocabulary',
        difficulty: 'beginner',
        estimatedMinutes: 9,
        xpReward: 70,
        isCompleted: false,
        isLocked: true,
      },
    ],
  },
  {
    id: 'unit-3',
    title: 'Getting Around',
    titleNl: 'Onderweg',
    description: 'Navigate Dutch cities, transport, and directions.',
    order: 3,
    color: '#f59e0b',
    isCompleted: false,
    progress: 0,
    lessons: [
      {
        id: 'l-3-1',
        title: 'Directions',
        titleNl: 'De Weg Vragen',
        description: 'Ask for and give directions',
        unit: 3,
        order: 1,
        type: 'conversation',
        difficulty: 'intermediate',
        estimatedMinutes: 10,
        xpReward: 90,
        isCompleted: false,
        isLocked: true,
      },
      {
        id: 'l-3-2',
        title: 'Public Transport',
        titleNl: 'Openbaar Vervoer',
        description: 'Trams, trains, and buses in the Netherlands',
        unit: 3,
        order: 2,
        type: 'vocabulary',
        difficulty: 'intermediate',
        estimatedMinutes: 8,
        xpReward: 85,
        isCompleted: false,
        isLocked: true,
      },
    ],
  },
]

export const mockFlashcards: FlashCard[] = [
  { id: 'f-1', dutch: 'goedemorgen', english: 'good morning', phonetic: 'KHoo-deh-MOR-khen', category: 'Greetings', difficulty: 'easy', example: 'Goedemorgen! Hoe gaat het?', exampleTranslation: 'Good morning! How are you?' },
  { id: 'f-2', dutch: 'goedemiddag', english: 'good afternoon', phonetic: 'KHoo-deh-MID-dakh', category: 'Greetings', difficulty: 'easy' },
  { id: 'f-3', dutch: 'goedenavond', english: 'good evening', phonetic: 'KHoo-deh-NAH-fohnt', category: 'Greetings', difficulty: 'easy' },
  { id: 'f-4', dutch: 'tot ziens', english: 'goodbye', phonetic: 'tot ZEENS', category: 'Greetings', difficulty: 'easy', example: 'Tot ziens! Tot morgen.', exampleTranslation: 'Goodbye! See you tomorrow.' },
  { id: 'f-5', dutch: 'dank je wel', english: 'thank you', phonetic: 'dank yuh vel', category: 'Greetings', difficulty: 'easy' },
  { id: 'f-6', dutch: 'alsjeblieft', english: 'please / here you go', phonetic: 'als-yuh-BLEEFT', category: 'Greetings', difficulty: 'medium' },
  { id: 'f-7', dutch: 'brood', english: 'bread', phonetic: 'broht', category: 'Food', difficulty: 'easy' },
  { id: 'f-8', dutch: 'kaas', english: 'cheese', phonetic: 'kahs', category: 'Food', difficulty: 'easy' },
  { id: 'f-9', dutch: 'koffie', english: 'coffee', phonetic: 'KOF-ee', category: 'Food', difficulty: 'easy' },
  { id: 'f-10', dutch: 'thee', english: 'tea', phonetic: 'tay', category: 'Food', difficulty: 'easy' },
  { id: 'f-11', dutch: 'bier', english: 'beer', phonetic: 'beer', category: 'Food', difficulty: 'easy' },
  { id: 'f-12', dutch: 'wijn', english: 'wine', phonetic: 'vayn', category: 'Food', difficulty: 'easy' },
  { id: 'f-13', dutch: 'straat', english: 'street', phonetic: 'straht', category: 'Navigation', difficulty: 'easy' },
  { id: 'f-14', dutch: 'links', english: 'left', phonetic: 'links', category: 'Navigation', difficulty: 'easy' },
  { id: 'f-15', dutch: 'rechts', english: 'right', phonetic: 'rekhts', category: 'Navigation', difficulty: 'easy' },
  { id: 'f-16', dutch: 'rechtdoor', english: 'straight ahead', phonetic: 'REKHT-dohr', category: 'Navigation', difficulty: 'medium' },
]

export const mockDecks: FlashcardDeck[] = [
  {
    id: 'd-1',
    title: 'Greetings & Phrases',
    description: 'Essential Dutch greetings and everyday phrases',
    cardCount: 20,
    category: 'Basics',
    color: '#3b82f6',
    progress: 65,
  },
  {
    id: 'd-2',
    title: 'Food & Drink',
    description: 'Vocabulary for restaurants, cafes, and supermarkets',
    cardCount: 35,
    category: 'Daily Life',
    color: '#f59e0b',
    progress: 30,
  },
  {
    id: 'd-3',
    title: 'Getting Around',
    description: 'Directions, transport, and navigation in Dutch cities',
    cardCount: 28,
    category: 'Travel',
    color: '#8b5cf6',
    progress: 0,
  },
  {
    id: 'd-4',
    title: 'Numbers & Time',
    description: 'Count, tell the time, and discuss dates',
    cardCount: 25,
    category: 'Basics',
    color: '#10b981',
    progress: 80,
  },
]

export const mockAchievements: Achievement[] = [
  { id: 'a-1', title: 'First Steps', description: 'Complete your first lesson', icon: '👣', isEarned: true, earnedAt: '2024-01-20' },
  { id: 'a-2', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '🔥', isEarned: true, earnedAt: '2024-01-27' },
  { id: 'a-3', title: 'Vocabulary Builder', description: 'Learn 50 Dutch words', icon: '📚', isEarned: true, earnedAt: '2024-01-25' },
  { id: 'a-4', title: 'Speed Learner', description: 'Complete 3 lessons in one day', icon: '⚡', isEarned: false },
  { id: 'a-5', title: 'Flashcard Master', description: 'Review 100 flashcards', icon: '🃏', isEarned: false },
  { id: 'a-6', title: 'Perfect Score', description: 'Get 100% on any lesson', icon: '⭐', isEarned: false },
]
